apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mongo-init
          image: mongo:7.0
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          command:
            - sh
            - -c
            - |
              until mongosh --host mongodb --username admin --password password --authenticationDatabase admin --eval "db.adminCommand('ping')" >/dev/null 2>&1; do
                echo "Waiting for MongoDB..."
                sleep 2
              done

              echo "Running init scripts..."
              mongosh --host mongodb --username admin --password password --authenticationDatabase admin /scripts/users.js
              mongosh --host mongodb --username admin --password password --authenticationDatabase admin /scripts/catalogue.js
              
              echo "Mongo init completed"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: mongo-init-scripts