version: '3.8'
services:
  load:
    build: ./load-gen
    image: robots/load-gen:v1.0
    container_name: load-gen
    environment:
      HOST: http://web:8080
      SILENT: "1"
      NUM_CLIENTS: "10"
      RUN_TIME: "600"
    depends_on:
      - web
    networks:
      - microservices
    profiles:
      - testing
