{
 "title": "MySQL Production Dashboard (Exporter)",
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "MySQL Up",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "mysql_up{job=\"mysql-exporter\"}"
    }
   ]
  },
  {
   "title": "Connections %",
   "type": "gauge",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{job=\"mysql-exporter\"} / mysql_global_variables_max_connections{job=\"mysql-exporter\"} * 100"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{job=\"mysql-exporter\"}[1m])"
    }
   ]
  },
  {
   "title": "Threads Running",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 10, "w": 6, "h": 6 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_running{job=\"mysql-exporter\"}"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 10, "w": 6, "h": 6 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries{job=\"mysql-exporter\"}[5m])"
    }
   ]
  }
 ]
}