grafana:
  enabled: true

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server:9090
          uid: prometheus_uid

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          type: file
          options:
            path: /var/lib/grafana/dashboards

  dashboards:
    default:
      cluster:
        file: dashboards/cluster-dashboard.json
      business:
        file: dashboards/business-dashboard.json
      mysql:
        file: dashboards/mysql-dashboard.json