{{- range $name, $svc := .Values.services }}
{{- if ne $name "defaults" }}
{{- $defaults := $.Values.services.defaults }}
{{- $mergedSvc := merge (deepCopy $svc) $defaults }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  replicas: {{ $mergedSvc.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ $name }}
          image: "{{ $mergedSvc.image }}:{{ $mergedSvc.tag | default $.Values.global.imageTag }}"
          imagePullPolicy: IfNotPresent
          ports:
            {{- range $p := $mergedSvc.ports }}
            - containerPort: {{ $p.port }}
            {{- end }}

          # ---------------- ENV ----------------
          env:
            {{- range $key, $value := $mergedSvc.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

            {{- range $s := $mergedSvc.secrets }}
            - name: {{ $s.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $s.secret }}
                  key: {{ $s.key }}
            {{- end }}

          # ---------------- RESOURCES ----------------
          resources:
            {{- toYaml $mergedSvc.resources | nindent 12 }}

          # ---------------- PROBES ----------------
          {{- if $mergedSvc.probes.enabled }}
          {{- if $mergedSvc.probes.enabled }}
          startupProbe:
            httpGet:
              path: {{ $mergedSvc.probes.startupPath }}
              port: {{ (index $mergedSvc.ports 0).port }}
            initialDelaySeconds: {{ $mergedSvc.probes.startupInitialDelaySeconds | default 0 }}
            failureThreshold: 30
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: {{ $mergedSvc.probes.livenessPath }}
              port: {{ (index $mergedSvc.ports 0).port }}
            initialDelaySeconds: 80
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: {{ $mergedSvc.probes.readinessPath }}
              port: {{ (index $mergedSvc.ports 0).port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
          {{- end }}

---
{{- end }}
{{- end }}