{{- range $name, $svc := .Values.services }}
{{- if ne $name "defaults" }}
{{- $svc = merge $svc $.Values.services.defaults }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  type: ClusterIP
  selector:
    app: {{ $name }}
  ports:
    {{- range $p := $svc.ports }}
    - name: {{ $p.name }}
      port: {{ $p.port }}
      targetPort: {{ $p.port }}
    {{- end }}
---
{{- end }}
{{- end }}