{{- range $name, $svc := .Values.services }}
{{- $defaults := $.Values.services.defaults }}
{{- $svcMerged := merge (deepCopy $defaults) $svc }}
{{- if $svcMerged.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $name }}-monitor
  labels:
    app: {{ $name }}
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Values.global.namespace | default "default" }}
  selector:
    matchLabels:
      app: {{ $name }}
  endpoints:
    - port: {{ $svcMerged.serviceMonitor.port }}
      path: {{ $svc.serviceMonitor.path }}
      interval: {{ $svcMerged.serviceMonitor.interval }}
---
{{- end }}
{{- end }}