apiVersion: v1
kind: Service
metadata:
  name: dispatch
  labels:
    app: dispatch
spec:
  type: ClusterIP
  selector:
    app: dispatch
  ports:
    - name: metrics
      port: {{ .Values.dispatch.service.port }}
      targetPort: {{ .Values.dispatch.service.port }}