apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
  labels:
    app: dispatch
spec:
  replicas: {{ .Values.dispatch.replicas }}
  selector:
    matchLabels:
      app: dispatch
  template:
    metadata:
      labels:
        app: dispatch
    spec:
      containers:
        - name: dispatch
          image: "{{ .Values.dispatch.image.repository }}:{{ .Values.dispatch.image.tag }}"
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: {{ .Values.dispatch.service.port }}

          env:
            - name: AMQP_HOST
              value: rabbitmq

            - name: DISPATCH_ERROR_PERCENT
              value: "0"

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi

          readinessProbe:
            httpGet:
              path: /metrics
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /metrics
              port: 9090
            initialDelaySeconds: 20
            periodSeconds: 20