apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongo-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: mongodb-exporter
  endpoints:
  - port: metrics
    interval: 15s