apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: {{ .Values.databases.mysql.service.port }}
    targetPort: {{ .Values.databases.mysql.service.port }}
  clusterIP: None
  selector:
    app: mysql