apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec:
  ports:
  - name: http
    port: {{ .Values.payment.service.port }}
    targetPort: {{ .Values.payment.service.port }}
  selector:
    app: payment