apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.ratings.service.port }}
    targetPort: {{ .Values.ratings.service.port }}
  selector:
    app: ratings