apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.shipping.service.port }}
    targetPort: {{ .Values.shipping.service.port }}
  selector:
    app: shipping