apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-job
spec:
  template:
    spec:
      containers:
      - name: mysql-init-container
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_SHIPPING_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: shipping-password
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "shipping"
        - name: MYSQL_PORT
          value: "3306"
        command: ["/bin/sh", "-c"]
        args:
        - |
          mysql -h${MYSQL_HOST} -P${MYSQL_PORT} -u root -p${MYSQL_ROOT_PASSWORD} <<EOF
          CREATE DATABASE IF NOT EXISTS cities;
          CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_SHIPPING_PASSWORD}';
          GRANT ALL PRIVILEGES ON cities.* TO '${MYSQL_USER}'@'%';
          FLUSH PRIVILEGES;
          EOF
      restartPolicy: OnFailure