apiVersion: v1
data:
  root-password: rooooot123@
  shipping-password: shipping123@
  ratings-password: ratings123@

kind: Secret
metadata:
  name: mysql-secret

# mysql -h shiping.mysql.database.azure.com -P 3306 -u shipping -pMahmoud1973@ cities < cities-dump.sql
# mysql -h shiping.mysql.database.azure.com -P 3306 -u shipping -pMahmoud1973@ cities < "C:\Users\Mahmoud Gamal\Desktop\Robots Microservices\mysql\scripts\cities-dump.sql"


# mysqldump --databases cities -h shiping.mysql.database.azure.com -P 3306 -u shipping -p"Mahmoud1973@" > cities.sql
# mysqldump -h shiping.mysql.database.azure.com -P 3306 -u shipping -p"Mahmoud1973@" cities > cities.sql

# mysql -h shiping.mysql.database.azure.com -P 3306 -u shipping -p"Mahmoud1973@"