grafana:
  adminUser: admin
  adminPassword: admin123

  forceDeployDatasources: true
  forceDeployDashboards: true

  ingress:
    enabled: false

  persistence:
    enabled: true
    size: 5Gi

  defaultDashboardsEnabled: true

  additionalDataSources:
    - name: Prometheus
      type: prometheus
      url: http://monitoring-kube-prometheus-prometheus:9090
      access: proxy
      isDefault: false

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

    retention: 7d

    serviceMonitorSelectorNilUsesHelmValues: false

    resources:
      requests:
        memory: 400Mi
        cpu: 200m
      limits:
        memory: 800Mi
        cpu: 500m

alertmanager:
  enabled: true

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

kube-state-metrics:
  enabled: true

nodeExporter:
  enabled: true

metricsServer:
  enabled: true