global:
  namespace: default
  imageTag: latest

ingress:
  enabled: true
  className: nginx         # azure-application-gateway

storageClassName: standard  # default or managed-csi

services:
  defaults:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    
    replicas: 1

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi

    probes:
      enabled: true
      startupPath: /health/live
      livenessPath: /health/live
      readinessPath: /health/ready

    env: {}

    ports:
      - name: http
        port: 8080

    hpa:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      cpuUtilization: 70

    serviceMonitor:
      enabled: false
      path: /metrics
      interval: 15s
      port: http

  cart:
    replicas: 2
    image: containerregistryrobots.azurecr.io/cart
    tag: v1.0.0

    env:
      REDIS_HOST: redis
      CATALOGUE_HOST: catalogue
      CART_SERVER_PORT: "8080"

    hpa:
      enabled: true

  catalogue:
    image: containerregistryrobots.azurecr.io/catalogue
    tag: v1.0.0

    env:
      MONGO_URL: "mongodb://$(MONGO_USER):$(MONGO_PASS)@mongodb:27017/catalogue?authSource=admin"
      GO_SLOW: "0"
      CATALOGUE_SERVER_PORT: "8080"

    secrets:
      - name: MONGO_USER
        secret: mongo-secret
        key: MONGO_INITDB_ROOT_USERNAME

      - name: MONGO_PASS
        secret: mongo-secret
        key: MONGO_INITDB_ROOT_PASSWORD

    hpa:
      enabled: true

  dispatch:
    image: containerregistryrobots.azurecr.io/dispatch
    tag: v1.0.0

    env:
      AMQP_HOST: rabbitmq
      DISPATCH_ERROR_PERCENT: "0"

    hpa:
      enabled: false

  payment:
    image: containerregistryrobots.azurecr.io/payment
    tag: v1.0.0

    env:
      CART_HOST: cart
      USER_HOST: user
      PAYMENT_GATEWAY: https://paypal.com/
      AMQP_HOST: rabbitmq
      PAYMENT_DELAY_MS: "0"

    secrets:
      - name: RABBITMQ_USER
        secret: rabbitmq-secret
        key: RABBITMQ_DEFAULT_USER

      - name: RABBITMQ_PASS
        secret: rabbitmq-secret
        key: RABBITMQ_DEFAULT_PASS

    hpa:
      enabled: false

  ratings:
    image: containerregistryrobots.azurecr.io/ratings
    tag: v1.0.0
    ports:
    - name: http
      port: 80

    env:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      MYSQL_HOST: mysql
      MYSQL_PORT: "3306"
      MYSQL_DB: ratings
      MYSQL_USER: ratings
      CATALOGUE_URL: "http://catalogue:8080"
    
    secrets:
      - name: MYSQL_PASSWORD
        secret: mysql-secret
        key: ratings-password

    probes:
      enabled: true
      startupPath: /_health
      livenessPath: /_health
      readinessPath: /_health

    hpa:
      enabled: true

  shipping:
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1024Mi
    probes:
      enabled: true
      startupPath: /actuator/health/liveness
      livenessPath: /actuator/health/liveness
      readinessPath: /actuator/health/readiness
      startupInitialDelaySeconds: 30

    image: containerregistryrobots.azurecr.io/shipping
    tag: v1.0.0

    env:
      CART_ENDPOINT: cart
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: cities
      DB_USER: shipping

    secrets:
      - name: DB_PASSWORD
        secret: mysql-secret
        key: shipping-password


    hpa:
      enabled: true

  user:
    image: containerregistryrobots.azurecr.io/user
    tag: v1.0.0

    env:
      MONGO_URL: "mongodb://$(MONGO_USER):$(MONGO_PASS)@mongodb:27017/users?authSource=admin"
      REDIS_HOST: "redis"

    secrets:
      - name: MONGO_USER
        secret: mongo-secret
        key: MONGO_INITDB_ROOT_USERNAME

      - name: MONGO_PASS
        secret: mongo-secret
        key: MONGO_INITDB_ROOT_PASSWORD

    hpa:
      enabled: true

# ---------------- Front ----------------

web:
  replicas: 2
  image: containerregistryrobots.azurecr.io/web
  tag: v1.0.0
  ports:
    - name: http
      port: 8080
    - name: metrics
      port: 9113

  env:
    CATALOGUE_HOST: catalogue
    USER_HOST: user
    CART_HOST: cart
    SHIPPING_HOST: shipping
    PAYMENT_HOST: payment
    RATINGS_HOST: ratings

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

  probes:
    enabled: true
    livenessPath: /health
    readinessPath: /health

  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    cpuUtilization: 70
      
  serviceMonitor:
    enabled: true
    path: /metrics
    interval: 15s
    port: exp-metrics

# ---------------- INFRA ----------------
databases:
  mongodb:
    image:
      repository: mongo
      tag: 7.0
    replicas: 1
    service:
      port: 27017
    storage: 5Gi

  mysql:
    image:
      repository: mysql
      tag: 8.0
    replicas: 1
    service:
      port: 3306
    storage: 10Gi

cache:
  redis:
    image:
      repository: redis
      tag: 7-alpine
    replicas: 1
    service:
      port: 6379
    storage: 1Gi

messaging:
  rabbitmq:
    image:
      repository: rabbitmq
      tag: 3.13-management-alpine
    replicas: 1
    service:
      amqpPort: 5672
      managementPort: 15672
      metricsPort: 15692
    storage: 5Gi