apiVersion: v1
kind: Service
metadata:
  name: dispatch
  labels:
    app: dispatch
spec:
  selector:
    app: dispatch
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
