apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shipping-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: shipping
  endpoints:
  - port: http
    path: /metrics
    interval: 15s