apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: containerregistryrobots.azurecr.io/shipping:v1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: cities
            - name: DB_USER
              value: shipping
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: shipping-password
            - name: CART_ENDPOINT
              value: cart
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 200m
              memory: 1000Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 150
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5