name: CI - GitOps Robot Shop

on:
  push:
    branches: [ main ]

env:
  REGISTRY: containerregistryrobots.azurecr.io

jobs:

# ---------------- DETECT CHANGES ----------------
  detect:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}

    steps:
      - uses: actions/checkout@v3

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            cart: services/cart/**
            catalogue: services/catalogue/**
            user: services/user/**
            payment: services/payment/**
            shipping: services/shipping/**
            ratings: services/ratings/**
            dispatch: services/dispatch/**
            web: services/web/**

# ---------------- BUILD + PUSH ----------------
  build:
    needs: detect
    runs-on: ubuntu-latest
    if: needs.detect.outputs.services != ''

    strategy:
      matrix:
        service: [cart, catalogue, user, payment, shipping, ratings, dispatch, web]

    steps:
      - uses: actions/checkout@v3

      - name: Check if service changed
        id: check
        run: |
          echo '${{ needs.detect.outputs.services }}' > changes.json
          echo "changed=$(jq -r '.${{ matrix.service }} // false' changes.json)" >> $GITHUB_OUTPUT

      - name: Login to ACR
        if: steps.check.outputs.changed == 'true'
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login $REGISTRY \
          -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Setup Buildx
        if: steps.check.outputs.changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Image
        if: steps.check.outputs.changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ matrix.service }}:${{ github.sha }}

# ---------------- UPDATE VALUES (GitOps) ----------------
  update-values:
    needs: build
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, 'Update image tag')"

    steps:
      - uses: actions/checkout@v3

      - name: Install yq
        run: sudo snap install yq

      - name: Update image tag in values.yaml
        run: |
          yq -i '.global.imageTag = "${{ github.sha }}"' infra/helm/values.yaml

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add infra/helm/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes"

          git push