apiVersion: batch/v1
kind: CronJob
metadata:
  name: loadgen-cron
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: loadgen
              image: containerregistryrobots.azurecr.io/rs-load:v1.0.0
              env:
                - name: HOST
                  value: "http://web:8080"
                - name: NUM_CLIENTS
                  value: "5"
                - name: RUN_TIME
                  value: "10m"